### ISSUE TITLE
Allow direct links

### ISSUE THREAD

**Issue by Erokaution** [HooferDevelops/url-music-discs#8]
This isn't a issue, but it very well could be one in the long run.

[Discord is making changes to it's CDN soon that will disallow people from just using Discord as a simple file host as we currently can.](https://www.bleepingcomputer.com/news/security/discord-will-switch-to-temporary-file-links-to-block-malware-delivery/) These changes will make all CDN links temporary and should be rolling out in the next couple months.
Youtube also infamously changes things on their end now and then, making YT-DLP unreliable occasionally.

For the longevity and stability of this mod, I am proposing you allow users to use any URL that points to a valid audio file.

I see from a closed issue that you made the urls limited to a whitelist for security reasons.
As a way to implement this, you could check a [files MIME](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#probeContentType%28java.nio.file.Path%29) to check if it's a audio file before downloading. Or if you want to be more rigorous, you can check for [file type signatures](https://en.wikipedia.org/wiki/List_of_file_signatures) manually once downloaded but before offloading to disk. Which I believe [this would do for you.](https://docs.oracle.com/javase/6/docs/api/java/net/URLConnection.html#guessContentTypeFromStream%28java.io.InputStream%29)
Or, at the very least, make the url whitelist a config option with it on by default.

**Comment by HaipaDev** [comment]
I am not the author, but I know they use YT DLP and while it has more endpoints im not sure about *any link* being able to work

Also, your issue is somewhat irrelevant, depending on how it all can be/is already resolved. Because the fact that cdn links will expire should mean nothing, as the files are downloaded locally to your .minecraft instance, so depending on how the actual disc detects the data to which file to point to based on link it should be all fine

**Comment by HooferDevelops** [comment]
Closing this as it is now supported in the latest version (1.2.0). Whitelisted URLs can be defined in the server config.
